# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Datum < Formula
  desc "datum is the client CLI for interacting with Datum Server"
  homepage "https://github.com/datumforge/datum"
  version "0.6.2"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/datumforge/datum/archive/refs/tags/v0.6.3.tar.gz"
      sha256 "5fd0b3b1976a3e53434b94010f3d33fa2c8788a0af976c9289f79c078b5f0947"

      def install
        bin.install "datum"
      end
    end
    on_arm do
      url "https://github.com/datumforge/datum/releases/download/v0.6.2/datum_0.6.2_darwin_arm64.tar.gz"
      sha256 "fc2a0a1325130b4061acdd70b2832a889c5189f205e978ab41864f7971e8a3ca"

      def install
        bin.install "datum"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/datumforge/datum/releases/download/v0.6.2/datum_0.6.2_linux_amd64.tar.gz"
        sha256 "3ac39d10692eeb1956a4d3979db1ae1c229d3906990ddc9c3fd41102e675cc2f"

        def install
          bin.install "datum"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/datumforge/datum/releases/download/v0.6.2/datum_0.6.2_linux_arm64.tar.gz"
        sha256 "f541f6f142568959e3f628071349099aa14e79f979b7b7e2abb96bf1b99c636a"

        def install
          bin.install "datum"
        end
      end
    end
  end

  test do
    system "#{bin}/datum --help"
  end
end
